In [1]:
#importing the dataset from the url
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00571/hcvdat0.csv"
df = pd.read_csv(url)

In [2]:
#removing unnecessary column
df = df.drop(["Unnamed: 0"],axis = 1)

In [3]:
#preprocessing the dataset

#label encoding the categorical data 

from sklearn.preprocessing import LabelEncoder

#creating an instance for sex category encoding

enc1 = LabelEncoder()
#adding new categorized column to the dataframe
df["Gen_cat"] = enc1.fit_transform(df["Sex"])
df

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Gen_cat
0,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,1
1,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,1
2,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,1
3,0=Blood Donor,32,m,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,1
4,0=Blood Donor,32,m,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,3=Cirrhosis,62,f,32.0,416.6,5.9,110.3,50.0,5.57,6.30,55.7,650.9,68.5,0
611,3=Cirrhosis,64,f,24.0,102.8,2.9,44.4,20.0,1.54,3.02,63.0,35.9,71.3,0
612,3=Cirrhosis,64,f,29.0,87.3,3.5,99.0,48.0,1.66,3.63,66.7,64.2,82.0,0
613,3=Cirrhosis,46,f,33.0,NaN,39.0,62.0,20.0,3.56,4.20,52.0,50.0,71.0,0
614,3=Cirrhosis,59,f,36.0,NaN,100.0,80.0,12.0,9.07,5.30,67.0,34.0,68.0,0

In [4]:
#encoding the target 

enc2 = LabelEncoder()

#addding encoded target value to the dataframe

df["Target"] = enc2.fit_transform(df["Category"])

In [8]:
df.head()

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Gen_cat,Target
0,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,1,0
1,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,1,0
2,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,1,0
3,0=Blood Donor,32,m,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,1,0
4,0=Blood Donor,32,m,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,1,0

In [11]:
#removing non numerical columns

df_new = df.drop(columns = ["Category","Sex"],axis = 1)
df_new

,Age,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Gen_cat,Target
0,32,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,1,0
1,32,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,1,0
2,32,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,1,0
3,32,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,1,0
4,32,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,62,32.0,416.6,5.9,110.3,50.0,5.57,6.30,55.7,650.9,68.5,0,4
611,64,24.0,102.8,2.9,44.4,20.0,1.54,3.02,63.0,35.9,71.3,0,4
612,64,29.0,87.3,3.5,99.0,48.0,1.66,3.63,66.7,64.2,82.0,0,4
613,46,33.0,NaN,39.0,62.0,20.0,3.56,4.20,52.0,50.0,71.0,0,4
614,59,36.0,NaN,100.0,80.0,12.0,9.07,5.30,67.0,34.0,68.0,0,4

In [23]:
#checking for NaN values in the dataset

df_new.isnull().sum()

Age         0
ALB         1
ALP        18
ALT         1
AST         0
BIL         0
CHE         0
CHOL       10
CREA        0
GGT         0
PROT        1
Gen_cat     0
Target      0
dtype: int64

In [30]:
#filling the NaN values

import numpy as np

df_new = df_new.fillna(method = "ffill")
df_new.isnull().sum()

Age        0
ALB        0
ALP        0
ALT        0
AST        0
BIL        0
CHE        0
CHOL       0
CREA       0
GGT        0
PROT       0
Gen_cat    0
Target     0
dtype: int64

In [31]:
#dividing the dataset in to features and target

X = df_new.drop(["Target"],axis = 1)
Y = df_new["Target"]

In [32]:
#splitting the dataset in to train and test splits

from sklearn.model_selection import train_test_split

X_tr, X_te, Y_tr, Y_te = train_test_split(X,Y,test_size = 0.2)

In [33]:
#building SVM models 
from sklearn import svm

#linear kernel 
sv1 =  svm.SVC(kernel = "linear", C = 1) 

#trainig the linear kernel

sv1.fit(X_tr, Y_tr)

SVC(C=1, kernel='linear')

In [34]:
#prediction on test data

Y_pre_l = sv1.predict(X_te)

In [43]:
#evaluating the linear kernel performance

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy of the linear Kernel = ", accuracy_score(Y_te,Y_pre_l))
print("Precision of the linear Kernel = ", precision_score(Y_te,Y_pre_l,average = 'macro'))
print("Recall of the linear Kernel = ", recall_score(Y_te,Y_pre_l,average = 'macro'))
print("F1 score of the linear Kernel = ", f1_score(Y_te,Y_pre_l,average = "macro"))

Accuracy of the linear Kernel =  0.9349593495934959
Precision of the linear Kernel =  0.5036687631027253
Recall of the linear Kernel =  0.5
F1 score of the linear Kernel =  0.5018172377985463

In [46]:
#polynomial kernel SVM 

sv2 = svm.SVC(kernel = "poly", C=1)

#training the polynomial kernel 

sv2.fit(X_tr,Y_tr)

SVC(C=1, kernel='poly')

In [47]:
#prediction on test data
Y_pre_p = sv2.predict(X_te)

In [50]:
#evaluating the performance in poly kernel

print("Accuracy of the polynomial Kernel = ", accuracy_score(Y_te,Y_pre_p))
print("Precision of the polynomial Kernel = ", precision_score(Y_te,Y_pre_p,average = 'macro'))
print("Recall of the polynomial Kernel = ", recall_score(Y_te,Y_pre_p,average = 'macro'))
print("F1 score of the polynomial Kernel = ", f1_score(Y_te,Y_pre_p,average = "macro"))

Accuracy of the polynomial Kernel =  0.926829268292683
Precision of the polynomial Kernel =  0.48792792792792794
Recall of the polynomial Kernel =  0.3888888888888889
F1 score of the polynomial Kernel =  0.4258317025440313

In [51]:
#rbf kernel svm
sv3 = svm.SVC(kernel = 'rbf', C = 1)

#training the model

sv3.fit(X_tr, Y_tr)

SVC(C=1)

In [52]:
#prediction on test data
Y_pre_r = sv3.predict(X_te)

In [53]:
#evaluating the performance in RBF kernel

print("Accuracy of the RBF Kernel = ", accuracy_score(Y_te,Y_pre_r))
print("Precision of the RBF Kernel = ", precision_score(Y_te,Y_pre_r,average = 'macro'))
print("Recall of the RBF Kernel = ", recall_score(Y_te,Y_pre_r,average = 'macro'))
print("F1 score of the RBF Kernel = ", f1_score(Y_te,Y_pre_r,average = "macro"))

Accuracy of the RBF Kernel =  0.9105691056910569
Precision of the RBF Kernel =  0.3511504424778761
Recall of the RBF Kernel =  0.28888888888888886
F1 score of the RBF Kernel =  0.3097608274078862

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [60]:
#implementing K-fold cross validation
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from numpy import mean,std
#for K = 10

kf10 = KFold(n_splits = 10, random_state=1,shuffle = True)

#Linear kernel model initialization

lc = svm.SVC(kernel = 'linear',C = 1)

#evaluating the linear kernel on K = 10 Kfold cross validation score
scores1 = cross_val_score(lc, X, Y, scoring='accuracy', cv=kf10, n_jobs=-1)
# report performance
print('Accuracy for linear kernel (K = 10): %.3f (%.3f)' % (mean(scores1), std(scores1)))

Accuracy for linear kernel (K = 10): 0.928 (0.027)

In [61]:
#for K = 5
kf5 = KFold(n_splits = 5, random_state=1,shuffle = True)

#Linear kernel model initialization

lc2 = svm.SVC(kernel = 'linear',C = 1)

#evaluating the linear kernel on K = 5 Kfold cross validation score
scores2 = cross_val_score(lc2, X, Y, scoring='accuracy', cv=kf5, n_jobs=-1)
# report performance
print('Accuracy for linear kernel (K = 5): %.3f (%.3f)' % (mean(scores2), std(scores2)))

Accuracy for linear kernel (K = 5): 0.924 (0.008)

In [62]:
#polynomial kernel initialization 

pk1 = svm.SVC(kernel = 'poly',C = 1)

#for k = 10
#evaluating the polynomial kernel on K = 10 Kfold cross validation score
scores3 = cross_val_score(pk1, X, Y, scoring='accuracy', cv=kf10, n_jobs=-1)
# report performance
print('Accuracy for polynomial kernel (K = 10): %.3f (%.3f)' % (mean(scores3), std(scores3)))

Accuracy for polynomial kernel (K = 10): 0.914 (0.029)

In [64]:
#for k = 5
pk2 = svm.SVC(kernel = 'poly',C = 1)


#evaluating the polynomial kernel on K = 5 Kfold cross validation score
scores4 = cross_val_score(pk2, X, Y, scoring='accuracy', cv=kf5, n_jobs=-1)
# report performance
print('Accuracy for polynomial kernel (K = 5): %.3f (%.3f)' % (mean(scores4), std(scores4)))

Accuracy for polynomial kernel (K = 5): 0.902 (0.022)

In [65]:
#rbf kernel

rbf1 = svm.SVC(kernel = 'rbf')
#for k = 10
#evaluating the rbf kernel on K = 10 Kfold cross validation score
scores5 = cross_val_score(rbf1, X, Y, scoring='accuracy', cv=kf10, n_jobs=-1)
# report performance
print('Accuracy for rbf kernel (K = 10): %.3f (%.3f)' % (mean(scores5), std(scores5)))

Accuracy for rbf kernel (K = 10): 0.901 (0.032)

In [66]:
#rbf kernel

rbf2 = svm.SVC(kernel = 'rbf')
#evaluating the rbf kernel on K = 5 Kfold cross validation score
scores6 = cross_val_score(rbf2, X, Y, scoring='accuracy', cv=kf5, n_jobs=-1)
# report performance
print('Accuracy for polynomial kernel (K = 5): %.3f (%.3f)' % (mean(scores6), std(scores6)))

Accuracy for polynomial kernel (K = 5): 0.904 (0.021)

In [75]:
#creating a dataframe table for interpreting the results 

values = [[mean(scores1),mean(scores3),mean(scores5)],[mean(scores2),mean(scores4),mean(scores6)]]
data = pd.DataFrame(values, index = ["10 Fold Cross Validation Accuracy","5 Fold Cross Validation Accuracy"])
data.columns = ["Linear Kernel", "Polynomial Kernel", "RBF Kernel"]
data

,Linear Kernel,Polynomial Kernel,RBF Kernel
10 Fold Cross Validation Accuracy,0.928345,0.913776,0.900820
5 Fold Cross Validation Accuracy,0.923577,0.902439,0.904065